### ISSUE TITLE
[BUG] Fluid input/outputs on buildings still present with omnifluid

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#181] opened 2020-05-06 20:58 UTC
**Describe the bug**
Buildings seem to still have fluid input/outputs on them not sure if this is intended behaviour but the assembly machine does not show its fluid input with a recipe

**To Reproduce**
Place down a building with a fluidbox expect the assembler

**Expected behavior**
since all liquids are items buildings should not have fluidboxes

**Screenshots**
![image](https://user-images.githubusercontent.com/13363284/81227512-e77fda80-902f-11ea-8eea-c9c6e80cf107.png)

**Additional context**

**Additional Info**
- Factorio Version: 18.22
- Minimal required mods to reproduce:
omnifluid
mod with a building as a fluidbox
- Savegame:

**Comment by Pezzawinkle** [comment] 2020-05-10 07:50
As far as im aware this is working as intended.
The fluids for boilers are partially excluded due to early complaints about the mod. And recipe that generates an exempt fluid keeps the fluidbox on the entity. Fluid may need a rewrite to get around this. For now, its low priority.

**Comment by Cereal-Sam** [comment] 2022-04-29 07:00
Has been fixed with the rewrite

**Closed by Cereal-Sam** 2022-04-29 07:00 UTC
Labels: enhancement, wontfix, Needs Discussion
